# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20180404_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=16)),
                ('s_age', models.IntegerField(default=18)),
                ('s_sex', models.BooleanField(default=False)),
            ],
        ),
    ]
