# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_grade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Grade'),
        ),
    ]
