# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=32, unique=True)),
                ('a_leg', models.IntegerField(default=4)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
