# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_flower'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='f_color',
            field=models.IntegerField(db_column='color', default=0),
        ),
    ]
