# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20180328_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ['-f_color']},
        ),
        migrations.AddField(
            model_name='flower',
            name='f_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
