# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dog',
            managers=[
                ('d_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
