# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20180329_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_num', models.CharField(max_length=18)),
                ('i_sex', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=16)),
                ('p_age', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='idcard',
            name='i_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.Person'),
        ),
    ]
