# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20180329_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='i_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='App.Person'),
        ),
    ]
