# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20180329_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=16)),
                ('h_cost', models.FloatField(default=1000)),
                ('h_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Person')),
            ],
        ),
    ]
