# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='h_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.Person'),
        ),
    ]
